### ISSUE TITLE
Merge Robofoundry changes?

### ISSUE THREAD

**Issue by samuk** [hippo5329/linorobot2_hardware#1]
Have you seen https://github.com/hippo5329/linorobot2_hardware/compare/master...robofoundry:linorobot2_hardware_hippo_esp32_fix:master

Some writeup [here](https://robofoundry.medium.com/building-cheapest-ros2-robot-using-esp32-part-1-hardware-build-af0044de68ce)

Are some of those changes worth merging back into your repo?

**Comment by hippo5329** [comment]
Yes. Some of Robofoundry fork are alreadymerged to my fork.

**Comment by hippo5329** [comment]
Yes. Some of Robofoundry fork are alreadymerged to my fork.
